---
version: 2
updates:
  # === Configuration for GitHub Actions ===
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "S0methingSomething"
    labels:
      - "dependencies"
      - "CI/CD"
    # --- BETTER COMMIT MESSAGE BLOCK ---
    commit-message:
      # Use a clear, conventional prefix. 'build' is common for dependency
      # updates.
      prefix: "build(deps)"
      # This ensures the prefix includes the scope (e.g., "build(deps):")
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      actions-updates:
        update-types:
          - "minor"
          - "patch"

  # === Configuration for Python (pip) with Top-Level Pinning ===
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "S0methingSomething"
    labels:
      - "dependencies"
      - "python"
    # --- BETTER COMMIT MESSAGE BLOCK ---
    commit-message:
      # Use the same prefix for consistency.
      prefix: "build(deps)"
      include: "scope"
    open-pull-requests-limit: 2
