version: 2
updates:
  # === Configuration for GitHub Actions ===
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "S0methingSomething"
    labels:
      - "dependencies"
      - "CI/CD"
    commit-message:
      prefix: "build(deps)"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      actions-updates:
        update-types:
          - "minor"
          - "patch"

  # === Configuration for Python with uv.lock ===
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "S0methingSomething"
    labels:
      - "dependencies"
      - "python"
      - "automerge" # Special label for our lockfile updater
    commit-message:
      prefix: "build(deps)"
      include: "scope"
    open-pull-requests-limit: 2
