version: 2
updates:
  # === Configuration for GitHub Actions ===
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "S0methingSomething"
    labels:
      - "dependencies"
      - "CI/CD"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      actions-updates:
        update-types:
          - "minor"
          - "patch"

  # === Configuration for Python (pip) with Top-Level Pinning ===
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "S0methingSomething"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(pip)"
      include: "scope"
    # A low limit is fine since you only have two packages to track.
    open-pull-requests-limit: 2
