version: '3.0'

scanning-settings:
  max-depth: 6
  exclude:
    - tests/
    - .venv/
    - .git/
    - __pycache__/
    - "*.pyc"
  include-files: []
  system:
    targets: []


report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: false  # Report all environment issues
        unpinned-requirements: false  # Warn about unpinned deps
      cvss-severity: []


fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - critical  # Always fail on critical
        - high      # Always fail on high
      exploitability:
        - critical
        - high

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch

installation:
  default-action: allow
  audit-logging:
    enabled: true
  allow:
    packages: []
    vulnerabilities: {}
  deny:
    packages: {}
    vulnerabilities:
      warning-on-any-of:
        cvss-severity:
          - medium  # Warn on medium severity
      block-on-any-of:
        cvss-severity:
          - critical
          - high


