# Configure which repositories the bot monitors and updates
[github]
sourceRepo = "S0methingSomething/BitEdit"
botRepo = "S0methingSomething/BitBot"
assetFileName = "MonetizationVars"

# Settings for posting and managing Reddit content.
[reddit]
subreddit = "BitTest1"
templateFile = "templates/post_template.md"
outdatedTemplateFile = "templates/outdated_template.md"
postTitle = "[BitBot] New MonetizationVars Release"
changelog_line_format = "* Updated {{display_name}} {{asset_name}} to version {{version}}"
botName = "BitBot"
creator = "C1oudyLol"
postMode = "direct_link" # Can be "direct_link" or "landing_page"
# custom_landing_template = "templates/landing_page.html" # Optional: Uncomment to use a custom HTML template.

# Controls how old posts are marked. mode can be 'overwrite' or 'inject'.
[outdatedPostHandling]
mode = "inject"
injectTemplateFile = "templates/inject_template.md"

# Text formats for GitHub releases.
[messages]
releaseTitle = "{{displayName}} MonetizationVars v{{version}}"
releaseDescription = "Automated release of the pre-patched `{{asset_name}}` file. All boolean values have been set to true."

# Defines tags for tutorial/comment blocks to be removed before posting.
[skipContent]
startTag = "<!-- TUTORIAL-START -->"
endTag = "<!-- TUTORIAL-END -->"

# Rules for analyzing Reddit comments and updating the post status.
[feedback]
statusLineFormat = "**Status:** {{status}} (based on comments)."
statusLineRegex = "^\\*\\*Status:\\*\\*.*$"

[feedback.labels]
working = "Working"
broken = "Potentially Not Working"
unknown = "Not enough feedback..."

workingKeywords = ["working", "works for me", "no issues", "perfect", "thanks"]
notWorkingKeywords = ["not working", "broken", "doesnt work"]
minFeedbackCount = 2

# Controls the adaptive polling interval for the comment checker (in seconds).
[timing]
firstCheck = 300
maxWait = 3600
increaseBy = 300

# Defines the keys to look for when parsing release descriptions.
[parsing]
app_key = "app"
version_key = "version"
asset_name_key = "asset_name"

# Configuration for each app the bot manages.
[[apps]]
id = "bitlife"
displayName = "BitLife"

[[apps]]
id = "bitlife_go"
displayName = "BitLife Go"