# --- GitHub Configuration ---
# sourceRepo: The original repository to monitor for new releases.
# botRepo: This bot's repository, where new releases will be created.
# assetFileName: The exact name of the asset file to download and patch.
github:
  sourceRepo: S0methingSomething/BitEdit
  botRepo: S0methingSomething/BitBot
  assetFileName: MonetizationVars

# --- Reddit Configuration ---
reddit:
  subreddit: BitTest1
  creator: C1oudyLol
  botName: BitBot
  # The issue number in botRepo used for persistent state storage.
  state_issue_number: 1

# --- Outdated Post Handling ---
# mode: 'inject' to add a notice at the top, 'overwrite' to replace the whole post.
outdatedPostHandling:
  mode: inject

# --- Message Templates ---
# Placeholders: {{asset_name}}, {{version}}, {{post_title}}, {{post_url}}, etc.
messages:
  releaseTitle: "{{asset_name}} v{{version}}"
  releaseDescription: "Automated release of the pre-patched `{{asset_name}}` file. All boolean values have been set to true."
  postTitle: "[BitBot] {{asset_name}} for BitLife v{{version}}"
  statusLine: "**Status:** {{status}} (based on comments)."

# --- Feedback Analysis Rules ---
feedback:
  statusLineRegex: '^\*\*Status:\*\*.*$'
  labels:
    working: Working
    broken: Potentially Not Working
    unknown: Not enough feedback...
  workingKeywords:
    - "working"
    - "works for me"
    - "no issues"
    - "perfect"
    - "thanks"
  notWorkingKeywords:
    - "not working"
    - "broken"
    - "doesnt work"
  minFeedbackCount: 2

# --- Adaptive Polling Timings (in seconds) ---
timing:
  firstCheck: 300
  maxWait: 3600
  increaseBy: 300

# --- Template Content Parsing ---
# Defines tags for tutorial/comment blocks to be removed before posting.
skipContent:
  startTag: "<!-- TUTORIAL-START -->"
  endTag: "<!-- TUTORIAL-END -->"

# --- Template File Configuration ---
# These files must exist inside the 'src/bitbot/templates/' directory.
templates:
  post: post_template.md
  outdated: outdated_template.md
  inject: inject_template.md
