steps:
  - name: Cache uv
    uses: actions/cache@v4
    with:
      path: ~/.cache/uv
      key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
      restore-keys: |
        ${{ runner.os }}-uv-

  - name: Install UV
    run: pipx install uv

  - name: Create Virtual Environment
    run: uv venv

  - name: Install dependencies
    run: uv pip sync --all-extras
