name: '[CI] Lint, Test, and Type Check'
on: [push, pull_request]

jobs:
  quality-checks:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install UV
        run: pipx install uv
      - name: Create venv and install dependencies
        # This command installs the project itself in editable mode, plus dev dependencies
        run: uv pip install -e .[dev]
      - name: Check formatting with Black
        run: uv run black --check .
      - name: Lint with Ruff
        run: uv run ruff check .
      - name: Type check with MyPy
        run: uv run mypy src
      - name: Run tests with Pytest
        run: uv run pytest --cov=bitbot --cov-report=xml
