---
name: '[Process] Lint PR Title-test'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
