name: '[Review] Automated PR Review'
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-and-comment:
    name: Run Linters with Reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      # action-ruff handles its own dependency installation
      - name: Run Ruff with Reviewdog
        uses: reviewdog/action-ruff@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          level: warning
          ruff_flags: 'src'
