name: BitBot Vercel Trigger (Alternative Scheduler)

on:
  workflow_dispatch:
  schedule:
    # This runs every 6 hours.
    - cron: '0 */6 * * *'

jobs:
  trigger-vercel-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel to run bot logic
        # This sends a GET request to a secret URL.
        # This is an alternative to using vercel.json for scheduling.
        run: curl -X GET "${{ secrets.VERCEL_TRIGGER_URL }}"
